MaterialTracker/Controllers/EditItemController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaterialTracker.ViewModels;
using Npgsql;

namespace MaterialTracker.Controllers
{
    public class EditItemController : Controller
    {
        public bool GetUserInfo()
        {
            string ADLogin = User.Identity.Name.Replace("STONE\\", "");

            using (var conn = new NpgsqlConnection(ExtensionMethod.ConnectionString_ERPSVR1))
            {
                //open the connection to the database
                conn.Open();
                using (var cmd = new NpgsqlCommand())
                {
                    //parse through the table based on the query string and add it into variable in class
                    cmd.Connection = conn;
                    cmd.CommandText = @"select likestobecalled || ' ' || LastName, employeeid from hr.tblhr_employees where active = '1' and ADLoginID like @ADLogin";
                    cmd.Parameters.AddWithValue("@ADLogin", ADLogin);

                    using (var reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ViewBag.UserName = reader.IsDBNull(0) ? "" : reader.GetString(0);
                            ViewBag.UserID = reader.IsDBNull(1) ? "" : reader.GetInt32(1).ToString();
                        }
                    }
                }
            }

            using (SqlConnection conn = new SqlConnection(ExtensionMethod.Get2016ServerConnectionString()))
            {
                string sql = @"select * from STONE_DB.dbo.permission_users where employee_id = @EmpID and permission_type_id = 36";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@EmpID", Convert.ToInt32(ViewBag.UserID));
                cmd.Connection.Open();

                using (var reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        return true;
                    }
                }
                cmd.Connection.Close();
            }

            return false;
        }

        // GET: AddItem
        public ActionResult Index()
        {
            ViewBag.EditPermission = GetUserInfo();
            EditMaterial newNode = new EditMaterial();
            MaterialsNode newNode2 = new MaterialsNode();

            ViewBag.tblid = Request.QueryString["tblid"] == null ? 0 : Convert.ToInt32(Request.QueryString["tblid"]);
            ViewBag.fmt = Request.QueryString["fmt"] == null ? 0 : Convert.ToInt32(Request.QueryString["fmt"]);
            ViewBag.SearchString = Request.QueryString["searchstring"] == null ? "" : Request.QueryString["searchstring"].ToString();

            ViewData["Item"] = newNode.myItems;
            ViewData["Vendor"] = newNode.myVendors;

            newNode2.LoadSingleItem(ViewBag.tblid, Convert.ToInt32(ViewBag.UserID));
            ViewBag.Title = "Edit " + newNode2.ItemNumber;
            ViewBag.SelectedItem = newNode2.ItemId;
            ViewBag.SelectedVendor = newNode2.VendorID;
            ViewBag.History = newNode2.History.ToString();

            return View(newNode2);
        }

        [HttpPost]
        public ActionResult Index(MaterialsNode model)
        {
            ViewBag.EditPermission = GetUserInfo();
            ModelState.Remove("mininv");
            ModelState.Remove("OrderFrequency");
            ModelState.Remove("MaxInventoryValue");
            ViewBag.tblid = Request.QueryString["tblid"] == null ? 0 : Convert.ToInt32(Request.QueryString["tblid"]);
            ViewBag.fmt = Request.QueryString["fmt"] == null ? 0 : Convert.ToInt32(Request.QueryString["fmt"]);
            ViewBag.SearchString = Request.QueryString["searchstring"] == null ? "" : Request.QueryString["searchstring"].ToString();

            if (ModelState.IsValid)
            {
                //Updates the usage so when the user is sent back to the page it is updated with new values
                model.GetWeeklyUsage();

                //Do save to the material tracker here
                using (SqlConnection conn = new SqlConnection(ExtensionMethod.Get2016ServerConnectionString()))
                {
                    string sql = @"update material_trackers set release_qty = @Release, order_frequency = @Order, vend_id = @Vend, lead_time = @Lead, updated_at = @Now, min_inv = @MinInv,
                                history_weight = @HisWeight, forecast_weight = @ForWeight, forecast = @Forecast, history = @History, low_usage = @LowUsage, new_item = @NewItem, user_watch = @UserWatch, 
                                max_inventory_value = @MaxValue where Id = @MatTrackID";
                    SqlCommand cmd = new SqlCommand(sql, conn);
                    cmd.Connection.Open();
                    cmd.Parameters.AddWithValue("@MatTrackID", Convert.ToInt32(ViewBag.tblid));
                    cmd.Parameters.AddWithValue("@Release", model.ReleaseQty);
                    cmd.Parameters.AddWithValue("@Order", model.OrderFrequency);
                    cmd.Parameters.AddWithValue("@Vend", model.VendorID);
                    cmd.Parameters.AddWithValue("@Lead", model.LeadTime);
                    cmd.Parameters.AddWithValue("@MinInv", model.MinInv);
                    cmd.Parameters.AddWithValue("@HisWeight", model.HistoryWeight);
                    cmd.Parameters.AddWithValue("@ForWeight", model.ForecastWeight);
                    cmd.Parameters.AddWithValue("@Forecast", model.Forecast);
                    cmd.Parameters.AddWithValue("@History", model.History);
                    cmd.Parameters.AddWithValue("@Now", DateTime.Now.AddDays(-1));
                    cmd.Parameters.AddWithValue("@LowUsage", DateTime.Now.AddDays(-1));
                    cmd.Parameters.AddWithValue("@NewItem", false);
                    cmd.Parameters.AddWithValue("@UserWatch", model.UpdateUserWatchString(model.SelectUserWatch, Convert.ToInt32(ViewBag.UserID), Convert.ToInt32(ViewBag.tblid)));
                    cmd.Parameters.AddWithValue("@MaxValue", model.MaxInventoryValue);
                    cmd.ExecuteNonQuery();
                    cmd.Connection.Close();
                }

                if (ViewBag.SearchString.ToString().Equals(""))
                {
                    return RedirectToAction("Index", "Home", new { ViewBag.fmt });
                }
                else
                {
                    return RedirectToAction("Index", "Home", new { ViewBag.SearchString });
                }
            }
            else
            {
                EditMaterial newNode = new EditMaterial();
                ViewData["Item"] = newNode.myItems;
                ViewData["Vendor"] = newNode.myVendors;
                ViewBag.Title = "Edit " + model.ItemNumber;
                ViewBag.SelectedItem = model.ItemId;
                ViewBag.SelectedVendor = model.VendorID;
                ViewBag.History = model.History.ToString();

                return View(model);
            }
        }
    }
}

MaterialTracker/Views/EditItem/Index.cshtml
@model MaterialTracker.ViewModels.MaterialsNode

@using (Html.BeginForm("Index", "EditItem", routeValues: new { ViewBag.tblid, ViewBag.fmt, ViewBag.SearchString }, method: FormMethod.Post))
{
    <div class="panel panel-default" style="width: 535px; margin: 0 auto; padding-bottom: 5px;">
        <div class="panel-heading">
            Edit Item
        </div>
        <div class="form-group" style="width: 500px; margin: 0 auto;">
            <h5>Item Number</h5>
            @Html.TextBoxFor(x => x.ItemNumber, new { @class = "form-control", @readonly = "readonly" })
            @Html.TextBoxFor(x => x.ItemId, new { @class = "form-control", style = "display:none" })
            <hr />
            @if (!Model.ItemDescription.Equals(""))
            {
                <h5>Item Description</h5>
                @Html.TextBoxFor(x => x.ItemDescription, new { @class = "form-control", @placeholder = "Item Description", @readonly = "readonly" })
                <hr />
            }
            <h5>Release Quantity</h5>
            @Html.ValidationMessageFor(x => x.ReleaseQty, null, new { @class = "text-danger" })
            @Html.TextBoxFor(x => x.ReleaseQty, new { @class = "form-control", @placeholder = "Release Quanity", @Value = (Model.ReleaseQty == -1 ? "" : Model.ReleaseQty.ToString()) })
            <hr />
            <h5>Order Frequency (Weeks)</h5>
            @Html.TextBoxFor(x => x.OrderFrequency, new { @class = "form-control", @placeholder = "Leave Blank for Auto Calculation", @Value = (Model.OrderFrequency == 0 ? "" : Model.OrderFrequency.ToString()) })
            <hr />
            <h5>Lead Time (Weeks)</h5>
            @Html.ValidationMessageFor(x => x.LeadTime, null, new { @class = "text-danger" })
            @Html.TextBoxFor(x => x.LeadTime, new { @class = "form-control", @placeholder = "Lead Time", @Value = (Model.LeadTime == -1 ? "" : Model.LeadTime.ToString()) })
            <hr />
            <h5>Minimum Inventory</h5>
            @Html.TextBoxFor(x => x.MinInv, new { @class = "form-control", @placeholder = "Leave Blank for Auto Calculation", @Value = (Model.MinInv == 0 ? "" : Model.MinInv.ToString()) })
            <hr />
            <h5>Maximum Inventory Value</h5>
            @Html.TextBoxFor(x => x.MaxInventoryValue, new { @class = "form-control", @placeholder = "Leave Blank for Auto Calculation", @Value = (Model.MaxInventoryValue == 0 ? "" : Model.MaxInventoryValue.ToString()) })
            <hr />
            <h5>Vendor</h5>
            @Html.ValidationMessageFor(x => x.VendorID, null, new { @class = "text-danger" })
            @Html.DropDownList("Vendors", ViewData["Vendor"] as List<SelectListItem>, new { @class = "form-control" })
            @Html.TextBoxFor(x => x.VendorID, new { @class = "form-control", style = "display:none" })
            <hr />
            <h5>
                My Materials
                @Html.CheckBoxFor(x => x.SelectUserWatch)
            </h5>
            <hr />
            @Html.ValidationMessageFor(x => x.UsageSelected, null, new { @class = "text-danger" })
            <p style="text-align: left">
                <h5>
                    History:
                    @Html.RadioButton("HistoryRadio", "0", new { @id = "option0" })@Html.Label("None")
                    @Html.RadioButton("HistoryRadio", "1", new { @id = "option1" })@Html.Label("1 Month")
                    @Html.RadioButton("HistoryRadio", "2", new { @id = "option2" })@Html.Label("2 Month")
                    @Html.RadioButton("HistoryRadio", "3", new { @id = "option3" })@Html.Label("3 Month")
                    @Html.TextBoxFor(x => x.History, new { style = "display:none" })

                    <span style="float: right;">
                        Forecast:
                        @Html.CheckBoxFor(x => x.Forecast)
                    </span>
                    @Html.CheckBoxFor(x => x.UsageSelected, new { @class = "form-control", style = "display:none" })
                </h5>
            </p>

            <div id="WeightDiv">
                <h5>
                    <p style="text-align: left">
                        History Weight
                        @Html.TextBoxFor(x => x.HistoryWeight, new { @readonly = "readonly", @style = "border:0; color:#000000; font-weight:bold; width: 35px; border-radius: 3px; padding-left: 2px;" })
                        <span style="float: right;">
                            Forecast Weight
                            @Html.TextBoxFor(x => x.ForecastWeight, new { @readonly = "readonly", @style = "border:0; color:#000000; font-weight:bold; width: 35px; border-radius: 3px; padding-left: 2px;" })
                        </span>
                    </p>
                </h5>
                <div id="slider-range-min"></div>
            </div>
            <hr />

            @*------------------               BUTTONS             -----------------------*@
            <p style="text-align: left">
                @if (!ViewBag.SearchString.Equals(""))
                {
                    @Html.ActionLink("Cancel", "Index", "Home", new { ViewBag.SearchString }, new { @class = "btn btn-default" })
                }
                else
                {
                    @Html.ActionLink("Cancel", "Index", "Home", new { ViewBag.fmt }, new { @class = "btn btn-default" })
                }
                @if (ViewBag.EditPermission == true)
                {
                    <span style="float: right;">
                        <input type="submit" name="submit" id="SaveButton" value="Save" class="btn btn-primary" />
                    </span>
                }
            </p>
        </div>
    </div>
}

@*------------------               JAVA             -----------------------*@
<script>
    $(function () {
        $("#Item").val(@ViewBag.SelectedItem);
        $("#Vendors").val(@ViewBag.SelectedVendor);
        var optionvalue = "option" + @ViewBag.History;

        var radiobtn = document.getElementById(optionvalue);
        radiobtn.checked = true;

        if ($('input[name=HistoryRadio]:checked').val() != '0' && $('input[name=Forecast]:checked').val() == 'true') {
            document.getElementById('WeightDiv').style.display = "block";
        }
        else {
            document.getElementById('WeightDiv').style.display = "none";
        }
    });

    //User changes item then we need to update the id to save it out
    $("#Item").change(function () {
        if ($("#Item").val() != "0") {
            document.getElementById("ItemId").value = $("#Item").val();

        } else {
            document.getElementById("ItemId").value = 0;
        }
    });

    //User Changes Vendor then we need to update the ID to save it out
    $("#Vendors").change(function () {
        if ($("#Vendors").val() != "0") {
            document.getElementById("VendorID").value = $("#Vendors").val();

        } else {
            document.getElementById("VendorID").value = 0;
        }
    });

    $(function () {
        $("#slider-range-min").slider({
            range: "min",
            value: $("#ForecastWeight").val(),
            min: 1,
            max: 99,
            slide: function (event, ui) {
                $("#ForecastWeight").val(ui.value);
                $("#HistoryWeight").val((100 - ui.value));
            }
        });
        $("#ForecastWeight").val($("#slider-range-min").slider("value"));
        $("#HistoryWeight").val((100 - $("#slider-range-min").slider("value")));
    });

    //On History Change
    $(':radio[name=HistoryRadio]').change(function () {
        $("#History").val($('input[name=HistoryRadio]:checked').val());

        if ($('input[name=HistoryRadio]:checked').val() != '0' || $('input[name=Forecast]:checked').val() == 'true') {
            document.getElementById('UsageSelected').checked = true;
        }
        else {
            document.getElementById('UsageSelected').checked = false;
        }

        //if both history and forecast selected then we show the weight bar otherwise we hide it
        if ($('input[name=HistoryRadio]:checked').val() != '0' && $('input[name=Forecast]:checked').val() == 'true') {
            document.getElementById('WeightDiv').style.display = "block";
            document.getElementById('UsageSelected').checked = true;
        }
        else {
            document.getElementById('WeightDiv').style.display = "none";
        }
    });

    //On Forecast Change
    $(':input[name=Forecast]').change(function () {
        //if both history and forecast selected then we show the weight bar otherwise we hide it
        if ($('input[name=HistoryRadio]:checked').val() != '0' || $('input[name=Forecast]:checked').val() == 'true') {
            document.getElementById('UsageSelected').checked = true;
        }
        else {
            document.getElementById('UsageSelected').checked = false;
        }


        if ($('input[name=HistoryRadio]:checked').val() != '0' && $('input[name=Forecast]:checked').val() == 'true') {
            document.getElementById('WeightDiv').style.display = "block";
        }
        else {
            document.getElementById('WeightDiv').style.display = "none";
        }
    });
</script>

@*------------------               CSS             -----------------------*@
<style type="text/css">
    @@media {
        .container {
            max-width: inherit !important;
            max-width: 97% !important;
        }
    }

    @@media (min-width: 0px) {
        .container {
            width: auto !important;
        }
    }

    body {
        padding-top: 0px !important;
        font-size: 1.5em !important;
    }

    .table > tbody > tr > td {
        border: none;
        border-left: 1px solid #ddd;
        border-right: 1px solid #ddd;
    }

    .navbar-brand {
        color: #777 !important;
        font-size: 18px !important;
    }

    label {
        padding-left: 3px !important;
    }

    hr {
        margin-top: 7px !important;
        margin-bottom: 7px !important;
    }
</style>